language: python

sudo: false

install:
    pip install tox

script: tox

notifications:
  on_success: change
  on_failure: always

matrix:
  include:
    - python: 2.6
      env: TOXENV=py26
    - python: 2.7
      env: TOXENV=py27
    - python: 3.2
      env: TOXENV=py32
    - python: 3.3
      env: TOXENV=py33
    - python: 3.4
      env: TOXENV=py34
    - python: 3.5
      env: TOXENV=py35
    - python: 2.6
      env: TOXENV=py26 REQUESTS_VERSION="===2.2.1"
    - python: 2.7
      env: TOXENV=py27 REQUESTS_VERSION="===2.2.1"
    - python: 3.2
      env: TOXENV=py32 REQUESTS_VERSION="===2.2.1"
    - python: 3.3
      env: TOXENV=py33 REQUESTS_VERSION="===2.2.1"
    - python: 3.4
      env: TOXENV=py34 REQUESTS_VERSION="===2.2.1"
    - python: 3.5
      env: TOXENV=py35 REQUESTS_VERSION="===2.2.1"
    - env: TOXENV=py27-flake8
    - env: TOXENV=py34-flake8
    - env: TOXENV=docstrings
    - env: TOXENV=docs
    - env: TOXENV=readme
  allow_failures:
  - env: TOXENV=docstrings
