language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - pypy
# command to install dependencies, e.g. pip install -r requirements.txt
# --use-mirrors
install:
    pip install -r dev-requirements.txt
# # command to run tests, e.g. python setup.py test
script: py.test
notifications:
   on_success: change
   on_failure: change
